import { transliterateHindi } from "./transliterate-hindi";
import type {
  CleanTranscriptInput,
  TransliterateOptions,
  TransliteratedSegment,
  TransliteratedTranscript,
} from "./types";

/**
 * Transliterate a cleaned transcript from Devanagari into Latin-script Hinglish,
 * preserving the original text and all timestamps. Pure and deterministic — no
 * translation, persona generation, or embeddings. The source is only read.
 *
 * The output mirrors the input structure but each segment (and the full text)
 * carries both `originalText` and `transliteratedText`.
 */
export function transliterateTranscript(
  transcript: CleanTranscriptInput,
  options: TransliterateOptions = {},
): TransliteratedTranscript {
  const sourceSegments = transcript.segments ?? [];

  const segments: TransliteratedSegment[] = sourceSegments.map((segment) => ({
    originalText: segment.text,
    transliteratedText: transliterateHindi(segment.text, options),
    offset: segment.offset,
    duration: segment.duration,
  }));

  const originalText =
    transcript.text ?? sourceSegments.map((segment) => segment.text).join(" ");
  const transliteratedText = segments.map((segment) => segment.transliteratedText).join(" ");

  return {
    videoId: transcript.videoId,
    language: transcript.language ?? null,
    isAutoGenerated: transcript.isAutoGenerated ?? null,
    segments,
    originalText,
    transliteratedText,
    url: transcript.url ?? null,
    fetchedAt: transcript.fetchedAt ?? null,
    cleanedAt: transcript.cleanedAt ?? null,
    transliteratedAt: new Date().toISOString(),
    segmentCount: segments.length,
  };
}
