/**
 * Minimal shape of a cleaned transcript this transliterator reads. Declared here
 * so the feature is independent of the transcript-cleaner; any object with these
 * fields (e.g. a CleanTranscript JSON) can be transliterated.
 */
export interface CleanTranscriptSegmentInput {
  text: string;
  /** Start time in seconds. */
  offset: number;
  /** Segment duration in seconds. */
  duration: number;
}

export interface CleanTranscriptInput {
  videoId: string;
  language?: string | null;
  isAutoGenerated?: boolean | null;
  segments: CleanTranscriptSegmentInput[];
  text?: string;
  url?: string | null;
  fetchedAt?: string | null;
  cleanedAt?: string | null;
}

export interface TransliteratedSegment {
  /** Original Devanagari text, preserved verbatim. */
  originalText: string;
  /** Latin-script Hinglish transliteration (not a translation). */
  transliteratedText: string;
  /** Start time in seconds — preserved from the source. */
  offset: number;
  /** Segment duration in seconds — preserved from the source. */
  duration: number;
}

export interface TransliteratedTranscript {
  videoId: string;
  language: string | null;
  isAutoGenerated: boolean | null;
  segments: TransliteratedSegment[];
  /** Full original Devanagari text (segments joined). */
  originalText: string;
  /** Full transliterated Hinglish text (segments joined). */
  transliteratedText: string;
  url: string | null;
  fetchedAt: string | null;
  cleanedAt: string | null;
  /** When this transliteration was produced (ISO 8601). */
  transliteratedAt: string;
  segmentCount: number;
}

export interface TransliterateOptions {
  /**
   * Extra technical-term overrides (Devanagari spelling -> canonical Latin form),
   * merged over the built-in dictionary. Use to preserve additional product or
   * library names.
   */
  technicalTerms?: Record<string, string>;
  /** Capitalize the first letter of each sentence. Defaults to true. */
  capitalizeSentences?: boolean;
}

export type TransliterateStatus = "processed" | "skipped" | "failed";

export interface TransliterateItemResult {
  videoId: string;
  status: TransliterateStatus;
  /** Present for skipped/failed items, and for cached processed items. */
  reason?: string;
  /** Present for processed items. */
  filePath?: string;
  segmentCount?: number;
}

export interface TransliterateSummary {
  persona: string;
  sourceDir: string;
  outputDir: string;
  total: number;
  processed: number;
  skipped: number;
  failed: number;
  results: TransliterateItemResult[];
}

export interface TransliteratePersonaTranscriptsOptions {
  /** Persona id; results are written under `<dataRoot>/transliterated-transcripts/<persona>/`. */
  persona: string;
  /** Base data directory. Defaults to `<cwd>/src/data`. */
  dataRoot?: string;
  /** Source directory of cleaned transcript JSON files. Defaults to `<dataRoot>/cleaned-transcripts/<persona>/`. */
  sourceDir?: string;
  /** Skip videos whose transliterated JSON already exists. Defaults to true. */
  skipExisting?: boolean;
  /** Transliteration overrides forwarded to {@link TransliterateOptions}. */
  transliterate?: TransliterateOptions;
}
