import type {
  FetchTranscriptOptions,
  TranscriptSegment,
  VideoTranscript,
} from "./types";

const WATCH_URL = "https://www.youtube.com/watch?v=";
const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

interface CaptionTrack {
  baseUrl?: string;
  languageCode?: string;
  kind?: string;
}

function decodeEntitiesOnce(text: string): string {
  return text
    .replace(/&#(\d+);/g, (_, code: string) =>
      String.fromCharCode(Number.parseInt(code, 10)),
    )
    .replace(/&#x([0-9a-fA-F]+);/g, (_, code: string) =>
      String.fromCharCode(Number.parseInt(code, 16)),
    )
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

// Caption XML is frequently double-encoded (e.g. `&amp;#39;`), so decode twice.
function decodeEntities(text: string): string {
  return decodeEntitiesOnce(decodeEntitiesOnce(text));
}

function parseTranscriptXml(xml: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  const pattern = /<text start="([\d.]+)" dur="([\d.]+)"[^>]*>([\s\S]*?)<\/text>/g;

  let match: RegExpExecArray | null;
  while ((match = pattern.exec(xml)) !== null) {
    const text = decodeEntities(match[3]).replace(/\s+/g, " ").trim();
    if (!text) {
      continue;
    }
    segments.push({
      offset: Number.parseFloat(match[1]),
      duration: Number.parseFloat(match[2]),
      text,
    });
  }

  return segments;
}

function extractCaptionTracks(html: string): CaptionTrack[] {
  const parts = html.split('"captions":');
  if (parts.length <= 1) {
    return [];
  }

  try {
    const jsonBlock = parts[1].split(',"videoDetails')[0].replace(/\n/g, "");
    const parsed = JSON.parse(jsonBlock) as {
      playerCaptionsTracklistRenderer?: { captionTracks?: CaptionTrack[] };
    };
    return parsed.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  } catch {
    return [];
  }
}

function pickTrack(tracks: CaptionTrack[], lang?: string): CaptionTrack | undefined {
  if (lang) {
    const exact = tracks.find((track) => track.languageCode === lang);
    if (exact) {
      return exact;
    }
    const prefix = tracks.find((track) => track.languageCode?.startsWith(lang));
    if (prefix) {
      return prefix;
    }
  }

  return tracks[0];
}

/**
 * Default transcript provider: scrapes the public watch page for caption tracks
 * and downloads the timed-text XML, preserving per-segment timestamps.
 *
 * Returns `null` when the video has no usable captions (so the caller can skip
 * it). Throws only on unexpected network/HTTP failures.
 */
export async function fetchYouTubeTranscript(
  videoId: string,
  options: FetchTranscriptOptions = {},
): Promise<VideoTranscript | null> {
  const fetchImpl = options.fetchImpl ?? fetch;
  const headers = {
    "user-agent": USER_AGENT,
    "accept-language": options.lang ? `${options.lang},en;q=0.8` : "en",
  };

  const pageResponse = await fetchImpl(`${WATCH_URL}${videoId}`, {
    headers,
    ...(options.signal ? { signal: options.signal } : {}),
  });
  if (!pageResponse.ok) {
    throw new Error(
      `Failed to load watch page for ${videoId} (${pageResponse.status}).`,
    );
  }

  const html = await pageResponse.text();
  const tracks = extractCaptionTracks(html);
  const track = pickTrack(tracks, options.lang);
  if (!track?.baseUrl) {
    return null;
  }

  const xmlResponse = await fetchImpl(track.baseUrl, {
    headers,
    ...(options.signal ? { signal: options.signal } : {}),
  });
  if (!xmlResponse.ok) {
    throw new Error(
      `Failed to load caption track for ${videoId} (${xmlResponse.status}).`,
    );
  }

  const segments = parseTranscriptXml(await xmlResponse.text());
  if (segments.length === 0) {
    return null;
  }

  return {
    videoId,
    language: track.languageCode ?? null,
    isAutoGenerated: track.kind !== undefined ? track.kind === "asr" : null,
    segments,
    text: segments.map((segment) => segment.text).join(" "),
    url: `${WATCH_URL}${videoId}`,
    fetchedAt: new Date().toISOString(),
  };
}
