export interface TranscriptSegment {
  /** Segment text (HTML entities decoded, whitespace normalized). */
  text: string;
  /** Start time in seconds. */
  offset: number;
  /** Segment duration in seconds. */
  duration: number;
}

export interface VideoTranscript {
  videoId: string;
  /** BCP-47 language code of the caption track, if known. */
  language: string | null;
  /** True for auto-generated (ASR) captions, null when unknown. */
  isAutoGenerated: boolean | null;
  /** Timestamped segments, in order. */
  segments: TranscriptSegment[];
  /** Full transcript text (segments joined). */
  text: string;
  url: string;
  fetchedAt: string;
}

export interface FetchTranscriptOptions {
  /** Preferred caption language code (e.g. "en", "hi"). */
  lang?: string;
  /** Injectable for tests; defaults to global `fetch`. */
  fetchImpl?: typeof fetch;
  signal?: AbortSignal;
  /**
   * When true, log detailed diagnostics (available caption tracks, chosen
   * language, request endpoints, and HTTP status). Falls back to the
   * `TRANSCRIPT_DEBUG` env var when omitted.
   */
  debug?: boolean;
}

/**
 * A transcript provider resolves a video id to its transcript, or `null` when
 * the video has no usable transcript (captions disabled/missing). It should
 * throw only on unexpected failures (network/parse), which the downloader
 * records as `failed` without aborting the batch.
 */
export type TranscriptProvider = (
  videoId: string,
  options?: FetchTranscriptOptions,
) => Promise<VideoTranscript | null>;

export type TranscriptStatus = "processed" | "skipped" | "failed";

export interface TranscriptItemResult {
  videoId: string;
  status: TranscriptStatus;
  /** Present for skipped/failed items, and for cached processed items. */
  reason?: string;
  /** Present for processed items. */
  filePath?: string;
  /** Present for freshly downloaded items. */
  segmentCount?: number;
}

export interface TranscriptDownloadSummary {
  persona: string;
  outputDir: string;
  total: number;
  processed: number;
  skipped: number;
  failed: number;
  results: TranscriptItemResult[];
}

export interface DownloadTranscriptsOptions {
  /** Persona id; transcripts are saved under `<dataRoot>/transcripts/<persona>/`. */
  persona: string;
  /**
   * Video ids to consider, in priority order (newest first is recommended, since
   * only the first `maxVideos` are processed).
   */
  videoIds: string[];
  /**
   * Maximum number of videos to process from the start of `videoIds`. Defaults
   * to 20, which is enough for persona generation. Pass a large number to
   * process all collected videos.
   */
  maxVideos?: number;
  /** Transcript source. Defaults to the built-in YouTube provider. */
  provider?: TranscriptProvider;
  /** Base data directory. Defaults to `<cwd>/src/data`. */
  dataRoot?: string;
  /** Preferred caption language. */
  lang?: string;
  /** Number of videos fetched in parallel per batch. Defaults to 5. */
  concurrency?: number;
  /** Skip videos whose JSON file already exists. Defaults to true. */
  skipExisting?: boolean;
  fetchImpl?: typeof fetch;
  signal?: AbortSignal;
  /** Log detailed transcript-retrieval diagnostics. See {@link FetchTranscriptOptions.debug}. */
  debug?: boolean;
}
