import type {
  CleanTranscript,
  CleanTranscriptSegment,
  RawTranscriptInput,
} from "./types";

// --- Normalization ----------------------------------------------------------

function decodeEntitiesOnce(text: string): string {
  return text
    .replace(/&#(\d+);/g, (_, code: string) =>
      String.fromCharCode(Number.parseInt(code, 10)),
    )
    .replace(/&#x([0-9a-fA-F]+);/g, (_, code: string) =>
      String.fromCharCode(Number.parseInt(code, 16)),
    )
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

// Caption text is frequently double-encoded (e.g. `&amp;#39;`), so decode twice.
function decodeEntities(text: string): string {
  return decodeEntitiesOnce(decodeEntitiesOnce(text));
}

function normalizeUnicode(text: string): string {
  return (
    text
      .normalize("NFC")
      // Zero-width and BOM characters.
      .replace(/[\u200B-\u200D\uFEFF]/g, "")
      // Non-breaking and other unusual spaces -> regular space.
      .replace(/[\u00A0\u2007\u202F]/g, " ")
      // Smart quotes / dashes -> ASCII equivalents (does not affect Hindi text).
      .replace(/[\u2018\u2019]/g, "'")
      .replace(/[\u201C\u201D]/g, '"')
      .replace(/[\u2013\u2014]/g, "-")
      .replace(/\u2026/g, "...")
  );
}

function normalizePunctuationAndWhitespace(text: string): string {
  return (
    text
      // Collapse any whitespace runs to a single space.
      .replace(/\s+/g, " ")
      // Drop spaces before sentence punctuation.
      .replace(/\s+([,.!?;:])/g, "$1")
      // Ensure a single space after sentence punctuation when glued to a word.
      .replace(/([,.!?;:])(?=[^\s\d])/g, "$1 ")
      // Collapse repeated spaces introduced above.
      .replace(/\s{2,}/g, " ")
      .trim()
  );
}

// --- Noise stripping (within a segment) -------------------------------------

const NON_SPEECH_CUE = /\[(?:music|applause|laughter|cheering|noise|silence|inaudible|sound)\]/gi;
const URL_PATTERN =
  /\b(?:https?:\/\/|www\.)\S+|\b[a-z0-9-]+\.(?:com|net|org|io|ly|be|co|in|dev|app|me|tv|gg)\b(?:\/\S*)?/gi;
const SOCIAL_HANDLE = /(^|\s)@[a-z0-9._]{2,}/gi;

function stripNoise(text: string): string {
  return text
    .replace(NON_SPEECH_CUE, " ")
    .replace(URL_PATTERN, " ")
    .replace(SOCIAL_HANDLE, "$1");
}

// --- Promotional segment detection ------------------------------------------

/**
 * Strong promo signals. A segment matching any of these is treated as a
 * like/share/subscribe reminder or promotional boilerplate and dropped. These
 * are intentionally specific so genuine teaching, greetings, humor, and audience
 * interaction ("let me know what you think") are preserved.
 */
const PROMO_PATTERNS: RegExp[] = [
  /\bsubscrib\w*/i,
  /\b(?:hit|smash|tap)\b[^.?!]*\blike\b/i,
  /\blike\b[^.?!]*\b(?:button|video|share)\b/i,
  /\b(?:notification|bell)\b[^.?!]*\b(?:icon|button|bell)?\b/i,
  /\bhit the bell\b/i,
  /\blink(?:s)?\b[^.?!]*\b(?:in|below)\b[^.?!]*\b(?:description|bio|comment)\b/i,
  /\bdescription\b[^.?!]*\blink\b/i,
  /\blike\b[^.?!]*\bshare\b[^.?!]*\bsubscrib\w*/i,
  /\bcheck out\b[^.?!]*\b(?:my|our)\b[^.?!]*\b(?:course|channel|playlist)\b/i,
];

function isPromotional(text: string): boolean {
  return PROMO_PATTERNS.some((pattern) => pattern.test(text));
}

// --- Segment cleaning --------------------------------------------------------

function cleanSegmentText(rawText: string): string {
  const decoded = decodeEntities(rawText ?? "");
  const normalized = normalizeUnicode(decoded);
  const withoutNoise = stripNoise(normalized);
  return normalizePunctuationAndWhitespace(withoutNoise);
}

/**
 * Clean a raw transcript into a {@link CleanTranscript}, preserving each kept
 * segment's timestamps. Applies noise removal, promo/boilerplate dropping,
 * consecutive-duplicate removal, and normalization. Never translates: Hindi and
 * English technical terms are preserved exactly.
 */
export function cleanTranscript(input: RawTranscriptInput): CleanTranscript {
  const sourceSegments = Array.isArray(input.segments) ? input.segments : [];
  const cleaned: CleanTranscriptSegment[] = [];
  let previousComparable = "";

  for (const segment of sourceSegments) {
    const text = cleanSegmentText(segment.text);

    if (!text) {
      continue;
    }
    if (isPromotional(text)) {
      continue;
    }

    const comparable = text.toLowerCase();
    if (comparable === previousComparable) {
      continue;
    }
    previousComparable = comparable;

    cleaned.push({
      text,
      offset: segment.offset,
      duration: segment.duration,
    });
  }

  return {
    videoId: input.videoId,
    language: input.language ?? null,
    isAutoGenerated: input.isAutoGenerated ?? null,
    segments: cleaned,
    text: cleaned.map((segment) => segment.text).join(" "),
    url: input.url ?? null,
    fetchedAt: input.fetchedAt ?? null,
    cleanedAt: new Date().toISOString(),
    sourceSegmentCount: sourceSegments.length,
    cleanedSegmentCount: cleaned.length,
  };
}
