/**
 * Minimal shape of a downloaded transcript this cleaner reads. Declared here so
 * the cleaner is independent of the transcript-downloader feature; any object
 * with these fields (e.g. a VideoTranscript JSON) can be cleaned.
 */
export interface RawTranscriptSegment {
  text: string;
  offset: number;
  duration: number;
}

export interface RawTranscriptInput {
  videoId: string;
  language?: string | null;
  isAutoGenerated?: boolean | null;
  segments: RawTranscriptSegment[];
  url?: string;
  fetchedAt?: string;
}

export interface CleanTranscriptSegment {
  /** Cleaned, normalized text. Never empty. */
  text: string;
  /** Start time in seconds — preserved from the source segment. */
  offset: number;
  /** Segment duration in seconds — preserved from the source segment. */
  duration: number;
}

export interface CleanTranscript {
  videoId: string;
  language: string | null;
  isAutoGenerated: boolean | null;
  /** Timestamped cleaned segments, in order. */
  segments: CleanTranscriptSegment[];
  /** Full cleaned transcript text (segments joined with a space). */
  text: string;
  url: string | null;
  /** When the source transcript was downloaded, if known. */
  fetchedAt: string | null;
  /** When this cleaned transcript was produced (ISO 8601). */
  cleanedAt: string;
  sourceSegmentCount: number;
  cleanedSegmentCount: number;
}

export type CleanTranscriptStatus = "processed" | "skipped" | "failed";

export interface CleanTranscriptItemResult {
  videoId: string;
  status: CleanTranscriptStatus;
  /** Present for skipped/failed items. */
  reason?: string;
  /** Present for processed items. */
  filePath?: string;
  cleanedSegmentCount?: number;
}

export interface CleanTranscriptSummary {
  persona: string;
  sourceDir: string;
  outputDir: string;
  total: number;
  processed: number;
  skipped: number;
  failed: number;
  results: CleanTranscriptItemResult[];
}

export interface CleanPersonaTranscriptsOptions {
  /** Persona id; cleaned files are written under `<dataRoot>/cleaned-transcripts/<persona>/`. */
  persona: string;
  /** Base data directory. Defaults to `<cwd>/src/data`. */
  dataRoot?: string;
  /** Source directory of raw transcript JSON files. Defaults to `<dataRoot>/transcripts/<persona>/`. */
  sourceDir?: string;
  /** Skip videos whose cleaned JSON already exists. Defaults to true. */
  skipExisting?: boolean;
}
